### ISSUE TITLE
xdg_menu license

### ISSUE THREAD

**Issue by GoogleCodeExporter** [p5n/archlinux-stuff#3]
```
Arch Linux xdg_menu package states "GPL", but source code contains only obscure 
"All rights reserved". Is it GPL-licensed after all? Was author permission to 
freely use the code ever received or do I have yet contact him?

```

Original issue reported on code.google.com by `Rvach...@nxt.ru` on 24 Oct 2012 at 7:51

**Comment by brutalcrozt** [comment]
would be happy to see update on this, but looks like it take a year or two?

**Comment by p5n** [comment]
Code derived from suse package which looks GPL2+, so this code has the same license, I will update it.
